TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(abspath ../../../rtl/fft8_stream.sv)
TOPLEVEL = fft8_stream
MODULE = test_fft
COMPILE_ARGS += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim

