TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(abspath ../../../rtl/axis_complex_fir.sv)
TOPLEVEL = axis_complex_fir
MODULE = test_fir
COMPILE_ARGS += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim

