TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(abspath ../../../rtl/axis_quarter_rate_mixer.sv)
TOPLEVEL = axis_quarter_rate_mixer
MODULE = test_mixer
COMPILE_ARGS += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim

