TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(abspath ../../../rtl/cordic_vector.sv)
TOPLEVEL = cordic_vector
MODULE = test_cordic
COMPILE_ARGS += -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim

